from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 684)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.camera_line = QtWidgets.QGroupBox(self.centralwidget)
        self.camera_line.setGeometry(QtCore.QRect(10, 10, 761, 441))
        self.camera_line.setObjectName("camera_line")
        self.camera_on = QtWidgets.QPushButton(self.camera_line)
        self.camera_on.setGeometry(QtCore.QRect(10, 20, 371, 31))
        self.camera_on.setObjectName("camera_on")
        self.camera_off = QtWidgets.QPushButton(self.camera_line)
        self.camera_off.setGeometry(QtCore.QRect(380, 20, 371, 31))
        self.camera_off.setObjectName("camera_off")
        self.camera = QtWidgets.QLabel(self.camera_line)
        self.camera.setGeometry(QtCore.QRect(10, 50, 741, 381))
        self.camera.setObjectName("camera")
        self.webcam = QtWidgets.QPushButton(self.camera)
        self.webcam.setGeometry(QtCore.QRect(120, 170, 93, 28))
        self.webcam.setObjectName("webcam")
        self.phone = QtWidgets.QPushButton(self.camera)
        self.phone.setGeometry(QtCore.QRect(320, 170, 93, 28))
        self.phone.setObjectName("phone")
        self.DSLR = QtWidgets.QPushButton(self.camera)
        self.DSLR.setGeometry(QtCore.QRect(520, 170, 93, 28))
        self.DSLR.setObjectName("DSLR")
        self.waiting_line = QtWidgets.QGroupBox(self.centralwidget)
        self.waiting_line.setGeometry(QtCore.QRect(780, 460, 281, 171))
        self.waiting_line.setObjectName("waiting_line")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.waiting_line)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 261, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.waiting_vbox = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.waiting_vbox.setContentsMargins(0, 0, 0, 0)
        self.waiting_vbox.setObjectName("waiting_vbox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.mask_waiting = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.mask_waiting.setObjectName("mask_waiting")
        self.horizontalLayout_5.addWidget(self.mask_waiting)
        self.mask_time = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.mask_time.setObjectName("mask_time")
        self.horizontalLayout_5.addWidget(self.mask_time)
        self.waiting_vbox.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.decibel_waiting = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.decibel_waiting.setObjectName("decibel_waiting")
        self.horizontalLayout_6.addWidget(self.decibel_waiting)
        self.decibel_time = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.decibel_time.setObjectName("decibel_time")
        self.horizontalLayout_6.addWidget(self.decibel_time)
        self.waiting_vbox.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.movement_waiting = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.movement_waiting.setObjectName("movement_waiting")
        self.horizontalLayout_4.addWidget(self.movement_waiting)
        self.movement_time = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.movement_time.setObjectName("movement_time")
        self.horizontalLayout_4.addWidget(self.movement_time)
        self.waiting_vbox.addLayout(self.horizontalLayout_4)
        self.state_line = QtWidgets.QGroupBox(self.centralwidget)
        self.state_line.setGeometry(QtCore.QRect(10, 460, 761, 171))
        self.state_line.setObjectName("state_line")
        self.state_reset_Button = QtWidgets.QPushButton(self.state_line)
        self.state_reset_Button.setGeometry(QtCore.QRect(650, 20, 101, 32))
        self.state_reset_Button.setObjectName("state_reset_Button")
        self.state_plainTextEdit = QtWidgets.QPlainTextEdit(self.state_line)
        self.state_plainTextEdit.setGeometry(QtCore.QRect(10, 50, 741, 111))
        self.state_plainTextEdit.setReadOnly(True)
        self.state_plainTextEdit.setObjectName("state_plainTextEdit")
        self.state_path_Button = QtWidgets.QPushButton(self.state_line)
        self.state_path_Button.setGeometry(QtCore.QRect(540, 20, 100, 32))
        self.state_path_Button.setObjectName("state_path_Button")
        self.state_function_Label = QtWidgets.QLabel(self.state_line)
        self.state_function_Label.setGeometry(QtCore.QRect(10, 20, 521, 32))
        self.state_function_Label.setStyleSheet("color : rgb(255, 0, 0)")
        self.state_function_Label.setObjectName("state_function_Label")
        self.function_line = QtWidgets.QGroupBox(self.centralwidget)
        self.function_line.setGeometry(QtCore.QRect(780, 10, 281, 441))
        self.function_line.setObjectName("function_line")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.function_line)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 261, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.function_vbox = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.function_vbox.setContentsMargins(0, 0, 0, 0)
        self.function_vbox.setObjectName("function_vbox")
        self.mask_detect = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.mask_detect.setObjectName("mask_detect")
        self.function_vbox.addWidget(self.mask_detect)
        self.mask_hbox = QtWidgets.QHBoxLayout()
        self.mask_hbox.setObjectName("mask_hbox")
        self.mask_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.mask_slider.setMinimum(0)
        self.mask_slider.setMaximum(50)
        self.mask_slider.setOrientation(QtCore.Qt.Horizontal)
        self.mask_slider.setObjectName("mask_slider")
        self.mask_hbox.addWidget(self.mask_slider)
        self.mask_lcd = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.mask_lcd.setObjectName("mask_lcd")
        self.mask_hbox.addWidget(self.mask_lcd)
        self.function_vbox.addLayout(self.mask_hbox)
        self.decibel_detect = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.decibel_detect.setObjectName("decibel_detect")
        self.function_vbox.addWidget(self.decibel_detect)
        self.decibel_hbox = QtWidgets.QHBoxLayout()
        self.decibel_hbox.setObjectName("decibel_hbox")
        self.decibel_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.decibel_slider.setMinimum(0)
        self.decibel_slider.setMaximum(50)
        self.decibel_slider.setOrientation(QtCore.Qt.Horizontal)
        self.decibel_slider.setObjectName("decibel_slider")
        self.decibel_hbox.addWidget(self.decibel_slider)
        self.decibel_lcd = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.decibel_lcd.setObjectName("decibel_lcd")
        self.decibel_hbox.addWidget(self.decibel_lcd)
        self.function_vbox.addLayout(self.decibel_hbox)
        self.movement_detect = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.movement_detect.setObjectName("movement_detect")
        self.function_vbox.addWidget(self.movement_detect)
        self.movement_hbox = QtWidgets.QHBoxLayout()
        self.movement_hbox.setObjectName("movement_hbox")
        self.movement_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.movement_slider.setMinimum(0)
        self.movement_slider.setMaximum(50)
        self.movement_slider.setOrientation(QtCore.Qt.Horizontal)
        self.movement_slider.setObjectName("movement_slider")
        self.movement_hbox.addWidget(self.movement_slider)
        self.movement_lcd = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.movement_lcd.setObjectName("movement_lcd")
        self.movement_hbox.addWidget(self.movement_lcd)
        self.function_vbox.addLayout(self.movement_hbox)
        self.save_run_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.save_run_button.setObjectName("save_run_button")
        self.function_vbox.addWidget(self.save_run_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1072, 24))
        self.menubar.setObjectName("menubar")
        self.menumenu = QtWidgets.QMenu(self.menubar)
        self.menumenu.setObjectName("menumenu")
        MainWindow.setMenuBar(self.menubar)
        self.actionsavew = QtWidgets.QAction(MainWindow)
        self.actionsavew.setObjectName("actionsavew")
        self.menumenu.addAction(self.actionsavew)
        self.menubar.addAction(self.menumenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "test"))
        self.camera_line.setTitle(_translate("MainWindow", "카메라 연결 화면"))
        self.camera_on.setText(_translate("MainWindow", "카메라 연결"))
        self.camera_off.setText(_translate("MainWindow", "카메라 끄기"))
        self.webcam.setText(_translate("MainWindow", "웹캠"))
        self.phone.setText(_translate("MainWindow", "핸드폰"))
        self.DSLR.setText(_translate("MainWindow", "DSLR"))
        self.waiting_line.setTitle(_translate("MainWindow", "재알림 대기시간"))
        self.mask_waiting.setText(_translate("MainWindow", "마스크 감지"))
        self.mask_time.setText(_translate("MainWindow", "00:00"))
        self.decibel_waiting.setText(_translate("MainWindow", "소음 감지"))
        self.decibel_time.setText(_translate("MainWindow", "00:00"))
        self.movement_waiting.setText(_translate("MainWindow", "마스크 미착욤 감지"))
        self.movement_time.setText(_translate("MainWindow", "00:00"))
        self.state_line.setTitle(_translate("MainWindow", "상태창"))
        self.state_reset_Button.setText(_translate("MainWindow", "초기화"))
        self.state_path_Button.setText(_translate("MainWindow", "저장 경로 설정"))
        self.state_function_Label.setText(_translate("MainWindow", "모든 기능 비활성화"))
        self.function_line.setTitle(_translate("MainWindow", "세부기능 및 알람간격 설정"))
        self.mask_detect.setText(_translate("MainWindow", "마스크감지"))
        self.decibel_detect.setText(_translate("MainWindow", "소음감지"))
        self.movement_detect.setText(_translate("MainWindow", "마스크 미착용 움직임 감지"))
        self.save_run_button.setText(_translate("MainWindow", "저장 및 실행"))
        self.menumenu.setTitle(_translate("MainWindow", "메뉴"))
        self.actionsavew.setText(_translate("MainWindow", "test"))
        self.actionsavew.setIconText(_translate("MainWindow", "test"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())